### PR TITLE
added uwu

### PR DESCRIPTION
**Pull request by Stellarnate**

### CODE REVIEW

**Comment by RoootTheFox** [comment]
the folder "Rooot's website_files" seems to just be a copy of the root directory

**Comment by Stellarnate** [comment]
ok lets try this again

**Comment by RoootTheFox** [comment]
you would need to update the hyperlink on the main page to run the change page function, otherwise it would direct to the page not seemlessly loading it

**Comment by RoootTheFox** [comment]
that should work now, lets merge it

**Pull request merged**
